### ISSUE TITLE
[Egg Request]: Taiga.io

### ISSUE THREAD

**Issue by H1ghSyst3m** [pelican-eggs/software#11]
### Does this expand an already existing service

No

### Link to a game or software

https://taiga.io/

### Links for the download

https://github.com/taigaio/taiga-docker

### Links for the install docs

https://community.taiga.io/t/taiga-30min-setup/170

**Comment by QuintenQVD0** [comment]
This can not be done as it needs a docker compose stack what wont work as it need multiple images
