### ISSUE TITLE
[Egg Request]: Icecast

### ISSUE THREAD

**Issue by sys-arch** [pelican-eggs/software#5]
### Does this expand an already existing service

Yes

### Link to a game or software

https://icecast.org/

### Links for the download

/

### Links for the install docs

/

**Comment by sys-arch** [comment]
This request was requested a long time ago in the old repository (https://github.com/pelican-eggs/eggs/issues/2020) but with the changes that have occurred, it has been forgotten and I come to rescue the request.

@QuintenQVD0 said he would take a look again.

**Comment by sys-arch** [comment]
Since the Pterodactyl team left to do their own project, these repositories are dead and show the total lack of interest of those responsible, so I'm closing this.

**Comment by QuintenQVD0** [comment]
> Since the Pterodactyl team left to do their own project, these repositories are dead and show the total lack of interest of those responsible, so I'm closing this.

thats up to you, just keep in mind that everyone does this in there free time.

**Comment by sys-arch** [comment]
It seems to me that in 3 months you have had some free time to respond to requests. Free time is not an excuse. I also have projects that I dedicate myself to in my free time but at least I try to respond to other people in a reasonable time. It's called education.

**Comment by QuintenQVD0** [comment]
> It seems to me that in 3 months you have had some free time to respond to requests. Free time is not an excuse. I also have projects that I dedicate myself to in my free time but at least I try to respond to other people in a reasonable time. It's called education.

I did not have notification on for this repo, and have 67 github open notification. I am trying my best but I am a student, yes I went on holiday, yes I work through the week, I love some time with my family on the weekend and soon will resume school. So the time I got went to the discord and to the best of my ability to this.

**Comment by gOOvER** [comment]
@sys-arch feel free to provide an Egg or pay someone, If you need such an Egg.

Its Open source and adding a requests here means Not, that the egg will be created. ;)

**Comment by sys-arch** [comment]
> I did not have notification on for this repo, and have 67 github open notification. I am trying my best but I am a student, yes I went on holiday, yes I work through the week, I love some time with my family on the weekend and soon will resume school. So the time I got went to the discord and to the best of my ability to this.

I appreciate your sincerity

> feel free to provide an Egg or pay someone

If I could, I would, but since I can't, I made the request. Is that why you allow these kinds of requests here?

> Its Open source and adding a requests here means Not, that the egg will be created. ;)

Since the change, lately he tends more to say "no" than "yes"

**Comment by gOOvER** [comment]
> > feel free to provide an Egg or pay someone
> 
> If I could, I would, but since I can't, I made the request. Is that why you allow these kinds of requests here?
> 
It is, but you want the egg fast as possible. As i said; there are a lot of people, which create eggs for money. If you cant wait, pay them ;)
